[package]
name = "vorbis-sys"
version = "0.0.2"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
build = "libvorbis/build.rs"
links = "vorbis"

[dependencies]
ogg-sys = "*"

[build-dependencies]
gcc = "*"
pkg-config = "*"
